### ISSUE TITLE
Bad return status for module build on kernel 4.12.6-1-ARCH

### ISSUE THREAD

**Issue by alefir** [astsam/rtl8812au#60]
Error occured while building DKMS module.
log below:
DKMS make.log for rtl8812au-r49.86fe67d for kernel 4.12.6-1-ARCH (x86_64)
Mon Aug 14 23:36:55 PDT 2017
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.12.6-1-ARCH/build M=/var/lib/dkms/rtl8812au/r49.86fe67d/build  modules
make[1]: Entering directory '/usr/lib/modules/4.12.6-1-ARCH/build'
  CC [M]  /var/lib/dkms/rtl8812au/r49.86fe67d/build/core/rtw_cmd.o
In file included from /var/lib/dkms/rtl8812au/r49.86fe67d/build/include/drv_types.h:32:0,
                 from /var/lib/dkms/rtl8812au/r49.86fe67d/build/core/rtw_cmd.c:22:
/var/lib/dkms/rtl8812au/r49.86fe67d/build/include/osdep_service.h: In function ‘thread_enter’:
/var/lib/dkms/rtl8812au/r49.86fe67d/build/include/osdep_service.h:343:2: error: implicit declaration of function ‘allow_signal’; did you mean ‘do_signal’? [-Werror=implicit-function-declaration]
  allow_signal(SIGTERM);
  ^~~~~~~~~~~~
  do_signal
/var/lib/dkms/rtl8812au/r49.86fe67d/build/include/osdep_service.h: In function ‘flush_signals_thread’:
/var/lib/dkms/rtl8812au/r49.86fe67d/build/include/osdep_service.h:353:6: error: implicit declaration of function ‘signal_pending’; did you mean ‘timer_pending’? [-Werror=implicit-function-declaration]
  if (signal_pending (current))
      ^~~~~~~~~~~~~~
      timer_pending
/var/lib/dkms/rtl8812au/r49.86fe67d/build/include/osdep_service.h:355:3: error: implicit declaration of function ‘flush_signals’; did you mean ‘do_signal’? [-Werror=implicit-function-declaration]
   flush_signals(current);
   ^~~~~~~~~~~~~
   do_signal
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:303: /var/lib/dkms/rtl8812au/r49.86fe67d/build/core/rtw_cmd.o] Error 1
make[1]: *** [Makefile:1515: _module_/var/lib/dkms/rtl8812au/r49.86fe67d/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.12.6-1-ARCH/build'
make: *** [Makefile:1264: modules] Error 2

**Comment by savir210** [comment]
I have this issue in Kali 4.14.0-kali3-amd64, was there ever a fix developed for this?

> make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.14.0-kali3-amd64/build M=/root/Downloads/RTL8812  modules
> make[1]: Entering directory '/usr/src/linux-headers-4.14.0-kali3-amd64'
>   CC [M]  /root/Downloads/RTL8812/core/rtw_cmd.o
> In file included from /root/Downloads/RTL8812/include/drv_types.h:32:0,
>                  from /root/Downloads/RTL8812/core/rtw_cmd.c:22:
> /root/Downloads/RTL8812/include/osdep_service.h: In function ‘thread_enter’:
> /root/Downloads/RTL8812/include/osdep_service.h:343:2: error: implicit declaration of function ‘allow_signal’; did you mean ‘do_signal’? [-Werror=implicit-function-declaration]
>   allow_signal(SIGTERM);
>   ^~~~~~~~~~~~
>   do_signal
> /root/Downloads/RTL8812/include/osdep_service.h: In function ‘flush_signals_thread’:
> /root/Downloads/RTL8812/include/osdep_service.h:353:6: error: implicit declaration of function ‘signal_pending’; did you mean ‘timer_pending’? [-Werror=implicit-function-declaration]
>   if (signal_pending (current))
>       ^~~~~~~~~~~~~~
>       timer_pending
> /root/Downloads/RTL8812/include/osdep_service.h:355:3: error: implicit declaration of function ‘flush_signals’; did you mean ‘do_signal’? [-Werror=implicit-function-declaration]
>    flush_signals(current);
>    ^~~~~~~~~~~~~
>    do_signal
> cc1: some warnings being treated as errors
> /usr/src/linux-headers-4.14.0-kali3-common/scripts/Makefile.build:319: recipe for target '/root/Downloads/RTL8812/core/rtw_cmd.o' failed
> make[4]: *** [/root/Downloads/RTL8812/core/rtw_cmd.o] Error 1
> /usr/src/linux-headers-4.14.0-kali3-common/Makefile:1525: recipe for target '_module_/root/Downloads/RTL8812' failed
> make[3]: *** [_module_/root/Downloads/RTL8812] Error 2
> Makefile:146: recipe for target 'sub-make' failed
> make[2]: *** [sub-make] Error 2
> Makefile:8: recipe for target 'all' failed
> make[1]: *** [all] Error 2
> make[1]: Leaving directory '/usr/src/linux-headers-4.14.0-kali3-amd64'
> Makefile:1264: recipe for target 'modules' failed
> make: *** [modules] Error 2
>
